Improve error and warning messages. Fix exit code.

diff --git a/danebot b/danebot
--- a/danebot
+++ b/danebot
@@ -94,8 +94,8 @@ detect_keyalg() {
     local default_ecdsa_curve="prime256v1"
 
     if [[ ! -f "$conf" ]]; then
-        printf "Renewal config '$conf' not found for lineage '$lineage'"
-        exit 2
+        printf "ERROR: Renewal config '$conf' not found for lineage '$lineage'"
+        exit 1
     fi
 
     # Initialise/Reset variables
@@ -112,7 +112,7 @@ detect_keyalg() {
         KEYALG="ecdsa"
         KEYOPTS=("ec_paramgen_curve:${key_curve:-$default_ecdsa_curve}")
         if [[ -z "$key_curve" ]]; then
-            printf "No ec_curve specified in $conf, falling back to default $default_ecdsa_curve for lineage '$lineage'"
+            printf "Warning: No ec_curve specified in $conf, falling back to default $default_ecdsa_curve for lineage '$lineage'"
         fi
     elif [[ "$key_type" == "rsa" || -z "$key_type" ]]; then
         # Extract RSA size if present
@@ -121,13 +121,13 @@ detect_keyalg() {
         KEYOPTS=("rsa_keygen_bits:${key_rsa:-$default_rsa_size}")
         if [[ -z "$key_rsa" ]]; then
             if [[ -z "$key_type" ]]; then
-                printf "No key_type specified in $conf, assuming default RSA for lineage '$lineage'"
+                printf "Warning: No key_type specified in $conf, assuming default RSA for lineage '$lineage'"
             fi
-            printf "No rsa_key_size specified in $conf, falling back to default $default_rsa_size for lineage '$lineage'"
+            printf "Warning: No rsa_key_size specified in $conf, falling back to default $default_rsa_size for lineage '$lineage'"
         fi
     else
-        printf "Unsupported key_type '$key_type' in $conf for lineage '$lineage'"
-        return 1
+        printf "ERROR: Unsupported key_type '$key_type' in $conf for lineage '$lineage'"
+        exit 1
     fi
 
     printf "Lineage '$lineage': using KEYALG=$KEYALG, KEYOPTS=${KEYOPTS[*]}"
